import "server-only";

// MOHD.HMS ENTERPRISE — Payslip PDF builder (spec §35).
// Uses the EXISTING centralized PdfDoc engine (§35 "do not create another PDF
// engine"). Money is pre-formatted through the central BND formatter.

import { PdfDoc, safeFilename, type TableCol } from "@/lib/hms/pdf/engine";
import type { Branding } from "@/lib/hms/pdf/branding";
import { fmtDate, money } from "@/lib/hms/format";
import { humanize } from "@/lib/hms/constants";
import type { PayrollLine } from "./config";

type PayslipRunInfo = {
  code: string;
  name: string;
  periodStart: Date;
  periodEnd: Date;
  payDate: Date | null;
  status: string;
  paymentRef: string;
};

type PayslipItemInfo = {
  id: string;
  employeeNo: string;
  employeeName: string;
  departmentName: string;
  positionName: string;
  basicCents: number;
  grossCents: number;
  deductionsCents: number;
  netCents: number;
  employerCostCents: number;
  linesJson: string;
};

const earningsCols: TableCol[] = [
  { header: "Component", width: 2.6 },
  { header: "Detail", width: 3.4 },
  { header: "Amount (BND)", width: 1.6, align: "right" },
];

function linesOf(item: PayslipItemInfo): PayrollLine[] {
  try {
    const parsed = JSON.parse(item.linesJson || "[]") as PayrollLine[];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export async function buildPayslipPdf(item: PayslipItemInfo, run: PayslipRunInfo, branding: Branding): Promise<{ bytes: Uint8Array; filename: string }> {
  const lines = linesOf(item);
  const earnings = lines.filter((l) => l.kind === "EARNING");
  const deductions = lines.filter((l) => l.kind === "DEDUCTION");
  const employer = lines.filter((l) => l.kind === "EMPLOYER");

  const doc = await PdfDoc.create(
    {
      company: branding.company,
      contactLines: branding.contactLines,
      docTitle: "Payslip",
      docNumber: `${run.code} · ${item.employeeNo}`,
      docDateLabel: `Pay date ${run.payDate ? fmtDate(run.payDate) : "—"}`,
      meta: [
        ["Period", `${fmtDate(run.periodStart)} – ${fmtDate(run.periodEnd)}`],
        ["Status", humanize(run.status)],
      ],
    },
    branding.logoBytes ?? null,
  );

  doc.kvGrid([
    ["Employee", item.employeeName],
    ["Employee ID", item.employeeNo],
    ["Department", item.departmentName || "—"],
    ["Position", item.positionName || "—"],
    ["Payroll Period", run.name],
    ["Pay Date", run.payDate ? fmtDate(run.payDate) : "Pending"],
  ]);
  doc.spacer(6);

  doc.heading("Earnings");
  doc.table(
    earningsCols,
    earnings.map((l) => [
      l.label + (l.basis ? `  (${l.basis})` : ""),
      l.detail || "—",
      money(l.amountCents),
    ]),
    { emptyHint: "No earnings recorded." },
  );
  doc.spacer(6);

  doc.heading("Deductions");
  doc.table(
    earningsCols,
    deductions.map((l) => [
      l.label + (l.basis ? `  (${l.basis})` : ""),
      l.detail || "—",
      money(l.amountCents),
    ]),
    { emptyHint: "No deductions." },
  );
  doc.spacer(6);

  // Backend-authoritative totals (§22 — net is the stored engine result).
  doc.totals([
    ["Gross Pay", money(item.grossCents)],
    ["Total Deductions", `− ${money(item.deductionsCents)}`],
    ["NET PAY", money(item.netCents)],
  ], { accent: true });

  if (employer.length > 0) {
    doc.heading("Employer Contributions");
    doc.para("Paid by the company — not deducted from the employee's salary (spec §19/§23).");
    doc.table(
      earningsCols,
      employer.map((l) => [l.label, l.detail || "—", money(l.amountCents)]),
    );
    doc.totals([["Total Employer Cost", money(item.employerCostCents)]]);
  }

  doc.banner("Currency: BND (Brunei Darussalam). All amounts in Brunei Dollars.");
  doc.notesBlock(
    "Notice",
    "This payslip is generated by MOHD.HMS ENTERPRISE from the approved payroll run and is confidential. The figures shown are the frozen values of the finalized payroll period (spec §46) — historical payslips are never recalculated.",
  );

  const built = await doc.build();
  return {
    bytes: built.bytes,
    filename: safeFilename(`MOHD-HMS-Payslip-${item.employeeNo}-${run.code}.pdf`),
  };
}
