// MOHD.HMS ENTERPRISE — WhatsApp attachment resolution (§31/§33/§61).
// Business documents are fetched from MinIO / generated by the CENTRAL PDF
// engine (the same immutable finalized documents the email channel uses).
// Bytes never persist to local disk and never duplicate storage — documents
// stay authoritative in MinIO; only references are recorded on the message.

import { db } from "@/lib/db";
import { storage } from "@/lib/hms/storage";
import { buildDocument, findDocumentType } from "@/lib/hms/pdf/documents";
import type { WhatsAppAttachmentKind } from "./types";

const SYSTEM_PDF_USER = { id: "system", role: "ADMIN", customerId: null };

export type ResolvedAttachment = {
  kind: WhatsAppAttachmentKind;
  filename: string;
  buffer: Buffer;
  contentType: string;
  ref: string;
};

const KIND_TO_DOC: Partial<Record<WhatsAppAttachmentKind, string>> = {
  QUOTATION_PDF: "quotation",
  INVOICE_PDF: "invoice",
  WO_PDF: "work-order",
  INSPECTION_PDF: "inspection-report",
};

/** Resolve attachment specs for a business event (quotation/invoice/…). */
export async function resolveAttachments(
  kinds: WhatsAppAttachmentKind[],
  ctx: { resourceType: string; resourceId: string },
): Promise<{ attachments: ResolvedAttachment[]; errors: string[] }> {
  const attachments: ResolvedAttachment[] = [];
  const errors: string[] = [];
  for (const kind of kinds) {
    try {
      const resolved = await resolveOne(kind, ctx);
      if (resolved) attachments.push(resolved);
      else errors.push(`${kind}: related document could not be resolved.`);
    } catch (e) {
      errors.push(`${kind}: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
  return { attachments, errors };
}

async function resolveOne(kind: WhatsAppAttachmentKind, ctx: { resourceType: string; resourceId: string }): Promise<ResolvedAttachment | null> {
  // HR letters: finalized PDF lives in MinIO under an immutable object key.
  if (kind === "LETTER_PDF") {
    const letterId = ctx.resourceType === "LETTER" ? ctx.resourceId : null;
    if (!letterId) return null;
    const letter = await db.letter.findUnique({ where: { id: letterId }, select: { letterNumber: true, pdfObjectKey: true, finalizedAt: true } });
    if (!letter?.pdfObjectKey || !letter.finalizedAt) return null;
    const obj = await storage.get(letter.pdfObjectKey);
    if (!obj) return null;
    return { kind, filename: `${letter.letterNumber}.pdf`, buffer: obj.buffer, contentType: "application/pdf", ref: `letter:${letterId}:${letter.pdfObjectKey}` };
  }

  // Payment receipt: the event points at the invoice — resolve latest payment.
  if (kind === "PAYMENT_RECEIPT_PDF") {
    if (ctx.resourceType !== "INVOICE") return null;
    const pay = await db.payment.findFirst({ where: { invoiceId: ctx.resourceId }, orderBy: { paidAt: "desc" }, select: { id: true } });
    if (!pay) return null;
    return buildFromEngine("payment-receipt", pay.id, `receipt-${pay.id}.pdf`);
  }

  const docType = KIND_TO_DOC[kind];
  if (!docType) return null;
  // The event's resourceId IS the entity. No other id source is accepted.
  return buildFromEngine(docType, ctx.resourceId);
}

async function buildFromEngine(docType: string, entityId: string, forceName?: string): Promise<ResolvedAttachment | null> {
  const def = findDocumentType(docType);
  if (!def) return null;
  const built = await buildDocument(def, entityId, SYSTEM_PDF_USER);
  if (!built?.bytes) return null;
  return {
    kind: (Object.keys(KIND_TO_DOC) as WhatsAppAttachmentKind[]).find((k) => KIND_TO_DOC[k] === docType) ?? "INVOICE_PDF",
    filename: forceName || `${docType}-${entityId}.pdf`,
    buffer: Buffer.from(built.bytes),
    contentType: "application/pdf",
    ref: `pdf-engine:${docType}:${entityId}`,
  };
}
