"use client";

// MOHD.HMS ENTERPRISE — Realtime event matrix (STEP 32).
// ONE authoritative mapping of business events → the module views they affect.
// Modules subscribe through this matrix (targeted invalidation, STEP 19) —
// never by hand-picking event strings inline.

export const RT = {
  // notifications
  NOTIFICATION_CREATED: "NOTIFICATION_CREATED",
  // complaint lifecycle
  COMPLAINT_CREATED: "COMPLAINT_CREATED",
  COMPLAINT_UPDATED: "COMPLAINT_UPDATED",
  COMPLAINT_ASSIGNED: "COMPLAINT_ASSIGNED",
  COMPLAINT_ACCEPTED: "COMPLAINT_ACCEPTED",
  COMPLAINT_STARTED: "COMPLAINT_STARTED",
  COMPLAINT_COMPLETED: "COMPLAINT_COMPLETED",
  COMPLAINT_CONFIRMED: "COMPLAINT_CONFIRMED",
  COMPLAINT_CLOSED: "COMPLAINT_CLOSED",
  // work orders
  WORK_ORDER_CREATED: "WORK_ORDER_CREATED",
  WORK_ORDER_UPDATED: "WORK_ORDER_UPDATED",
  WORK_ORDER_COMPLETED: "WORK_ORDER_COMPLETED",
  WO_OVERDUE: "WO_OVERDUE",
  // PM
  PM_DUE: "PM_DUE",
  PM_REMINDER: "PM_REMINDER",
  PM_OVERDUE: "PM_OVERDUE",
  PM_PLAN_UPDATED: "PM_PLAN_UPDATED",
  PM_TASK_UPDATED: "PM_TASK_UPDATED",
  // quotations
  QUOTATION_CREATED: "QUOTATION_CREATED",
  QUOTATION_UPDATED: "QUOTATION_UPDATED",
  QUOTATION_SENT: "QUOTATION_SENT",
  QUOTATION_ACCEPTED: "QUOTATION_ACCEPTED",
  // invoices / payments
  INVOICE_CREATED: "INVOICE_CREATED",
  INVOICE_UPDATED: "INVOICE_UPDATED",
  INVOICE_SENT: "INVOICE_SENT",
  INVOICE_OVERDUE: "INVOICE_OVERDUE",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  // inventory / purchasing
  LOW_STOCK: "LOW_STOCK",
  INVENTORY_ADJUSTED: "INVENTORY_ADJUSTED",
  INVENTORY_ITEM_UPDATED: "INVENTORY_ITEM_UPDATED",
  SUPPLIER_UPDATED: "SUPPLIER_UPDATED",
  PURCHASE_CREATED: "PURCHASE_CREATED",
  PURCHASE_UPDATED: "PURCHASE_UPDATED",
  PURCHASE_RECEIVED: "PURCHASE_RECEIVED",
  // IRMS
  IRMS_PROJECT_UPDATED: "IRMS_PROJECT_UPDATED",
  IRMS_REPORT_UPDATED: "IRMS_REPORT_UPDATED",
  IRMS_PHOTOS_UPDATED: "IRMS_PHOTOS_UPDATED",
  // centralized checklist engine
  CHECKLIST_GENERATED: "CHECKLIST_GENERATED",
  CHECKLIST_UPDATED: "CHECKLIST_UPDATED",
  CHECKLIST_COMPLETED: "CHECKLIST_COMPLETED",
  INSPECTION_SUBMITTED: "INSPECTION_SUBMITTED",
  INSPECTION_REVIEWED: "INSPECTION_REVIEWED",
  INSPECTION_APPROVED: "INSPECTION_APPROVED",
  INSPECTION_REJECTED: "INSPECTION_REJECTED",
  INSPECTION_ARCHIVED: "INSPECTION_ARCHIVED",
  INSPECTION_COMPLETED: "INSPECTION_COMPLETED",
  // entities
  EQUIPMENT_UPDATED: "EQUIPMENT_UPDATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  USER_UPDATED: "USER_UPDATED",
  HR_LEAVE_UPDATED: "HR_LEAVE_UPDATED",
  EMPLOYEE_UPDATED: "EMPLOYEE_UPDATED",
  // payroll (under HR)
  PAYROLL_RUN_UPDATED: "PAYROLL_RUN_UPDATED",
  PAYSLIP_PUBLISHED: "PAYSLIP_PUBLISHED",
  HR_OVERTIME_UPDATED: "HR_OVERTIME_UPDATED",
  VEHICLE_UPDATED: "VEHICLE_UPDATED",
  // system
  ESCALATE_COMPLAINT_NOT_ACCEPTED: "ESCALATE_COMPLAINT_NOT_ACCEPTED",
  SLA_BREACH_COMPLAINT: "SLA_BREACH_COMPLAINT",
} as const;

/** Events each module LIST PAGE refetches on (targeted, no full invalidation). */
export const MODULE_EVENTS: Record<string, string[]> = {
  dashboard: ["*"],
  complaints: [
    RT.COMPLAINT_CREATED, RT.COMPLAINT_UPDATED, RT.COMPLAINT_ASSIGNED, RT.COMPLAINT_ACCEPTED,
    RT.COMPLAINT_STARTED, RT.COMPLAINT_COMPLETED, RT.COMPLAINT_CONFIRMED, RT.COMPLAINT_CLOSED,
  ],
  "work-orders": [
    RT.WORK_ORDER_CREATED, RT.WORK_ORDER_UPDATED, RT.WORK_ORDER_COMPLETED, RT.WO_OVERDUE,
    RT.COMPLAINT_ACCEPTED, RT.COMPLAINT_STARTED, RT.COMPLAINT_COMPLETED,
    // checklist engine — a generated/approved checklist lands on the WO live
    RT.CHECKLIST_GENERATED, RT.CHECKLIST_UPDATED,
  ],
  invoices: [RT.INVOICE_CREATED, RT.INVOICE_UPDATED, RT.INVOICE_SENT, RT.INVOICE_OVERDUE, RT.PAYMENT_RECEIVED],
  payments: [RT.PAYMENT_RECEIVED, RT.INVOICE_SENT, RT.INVOICE_CREATED],
  quotations: [RT.QUOTATION_CREATED, RT.QUOTATION_UPDATED, RT.QUOTATION_SENT, RT.QUOTATION_ACCEPTED],
  inventory: [RT.LOW_STOCK, RT.INVENTORY_ADJUSTED, RT.INVENTORY_ITEM_UPDATED, RT.PURCHASE_RECEIVED, RT.SUPPLIER_UPDATED],
  purchases: [RT.PURCHASE_CREATED, RT.PURCHASE_UPDATED, RT.PURCHASE_RECEIVED],
  equipment: [RT.EQUIPMENT_UPDATED, RT.PM_TASK_UPDATED],
  pm: [RT.PM_DUE, RT.PM_REMINDER, RT.PM_OVERDUE, RT.PM_PLAN_UPDATED, RT.PM_TASK_UPDATED],
  irms: [
    RT.IRMS_PROJECT_UPDATED, RT.IRMS_REPORT_UPDATED, RT.IRMS_PHOTOS_UPDATED,
    RT.INSPECTION_SUBMITTED, RT.INSPECTION_REVIEWED, RT.INSPECTION_APPROVED,
    RT.INSPECTION_REJECTED, RT.INSPECTION_ARCHIVED, RT.INSPECTION_COMPLETED,
  ],
  /** Centralized checklist engine — list refetches on any instance mutation. */
  checklists: [RT.CHECKLIST_GENERATED, RT.CHECKLIST_UPDATED, RT.CHECKLIST_COMPLETED],
  /** Customer portal IRMS view — only customer-visible lifecycle events. */
  "irms-portal": [RT.INSPECTION_APPROVED, RT.IRMS_REPORT_UPDATED],
  customers: [RT.CUSTOMER_UPDATED],
  users: [RT.USER_UPDATED],
  employees: [RT.EMPLOYEE_UPDATED, RT.HR_LEAVE_UPDATED],
  hr: [RT.HR_LEAVE_UPDATED, RT.EMPLOYEE_UPDATED],
  finance: [RT.INVOICE_CREATED, RT.INVOICE_SENT, RT.PAYMENT_RECEIVED, RT.INVOICE_OVERDUE],
  payroll: [RT.PAYROLL_RUN_UPDATED, RT.PAYSLIP_PUBLISHED, RT.HR_OVERTIME_UPDATED],
  vehicles: [RT.VEHICLE_UPDATED],
  suppliers: [RT.SUPPLIER_UPDATED, RT.PURCHASE_RECEIVED],
};

/** Complaint-detail events (status timeline must stay live). */
export const COMPLAINT_DETAIL_EVENTS = MODULE_EVENTS.complaints;
/** Work-order-detail events. */
export const WO_DETAIL_EVENTS = MODULE_EVENTS["work-orders"];
/** Invoice-detail events. */
export const INVOICE_DETAIL_EVENTS = MODULE_EVENTS.invoices;
